version: '3'

services:
  docker-django-nginx:
    image: docker-django-nginx:latest
    build:
      context: .
      dockerfile: deploy/nginx/Dockerfile
    ports:
      - 8080:80
    volumes:
      - static:/app/static
    depends_on:
      - docker-django-app

  docker-django-app:
    image: docker-django-app:latest
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8000:8000
    depends_on: 
      - docker-django-db
    environment:
      DB_HOST: docker-django-db
    volumes:
      - static:/app/static

  docker-django-db:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

volumes:
  static: